apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: discord-bot-metrics
  namespace: discord-bot
  labels:
    app: discord-bot
    release: prometheus
spec:
  selector:
    matchLabels:
      app: discord-bot
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
---
apiVersion: v1
kind: Service
metadata:
  name: discord-bot-metrics
  namespace: discord-bot
  labels:
    app: discord-bot
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: discord-bot
