apiVersion: v1
kind: Service
metadata:
  name: discord-bot
  namespace: discord-bot
  labels:
    app: discord-bot
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: discord-bot
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
# Service for external monitoring (optional)
apiVersion: v1
kind: Service
metadata:
  name: discord-bot-metrics
  namespace: discord-bot
  labels:
    app: discord-bot
spec:
  type: ClusterIP
  selector:
    app: discord-bot
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
